# Reference https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#sharing-an-environment
name: ml-ci-cd-example
dependencies:
  - python=3.6
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyter
  - scikit-learn
  # Install package from specific channels - https://github.com/conda/conda/issues/7202
  - hesi_m::keras
